[target.xtensa-esp32-none-elf]
runner = "espflash --monitor"

[build]
rustflags = [
  "-C", "link-arg=-Trom_functions.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-Wl,--nmagic",
  "-C", "target-feature=-loop",
]
target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
